// src/components/InvalidConfig.vue
<template>
  <div v-show="onInvalid" class="row" id="gcim-invalid-config">
    <div class="eight wide column centered ">
      <div class="ui attached message">
        <div class="header">{{ headerText }}</div>
      </div>
      <div class="ui attached fluid segment">
        <p>
          Make sure all configs are set.
          The following properties must be defined in the URL.
        </p>
        <p>
          Check <a href="https://github.com/emilianoeloi/gitlab-ci-dashboard/blob/master/README.md">READ ME</a> for more configuration options.
        </p>
        <ul>
          <li>gitlab</li>
          <li>token</li>
          <li>projectsFile</li>
          <li>gitlabciProtocol (optional)</li>
          <li>hideSuccessCards (optional)</li>
          <li>hideVersion (optional)</li>
          <li>interval (optional)</li>
          <li>apiVersion (optional)</li>
        </ul>
        <p>projectsFile json pattern</p>
        <pre>
[
  {
    "description": "React Native render for draft.js model",
    "namespace": "globocom",
    "project": "react-native-draftjs-render",
    "branch": "develop"
  }
  (...)
]
        </pre>
      </div>
      <div class="ui bottom attached warning message">
        <p>Ex: https://emilianoeloi.github.io/gitlab-ci-dashboard/?gitlab=gitlab.com&token=w_zZcGZw-8pKxX_qSbWy&projectsFile=https://emilianoeloi.github.io/gitlab-ci-dashboard/static/gitlab.json</p>
        <h4>gitlab-ci-monitor compatibility</h4>
        <p>Ex: https://emilianoeloi.github.io/gitlab-ci-dashboard/?gitlab=gitlab.example.com&token=12345&projects=namespace/project1,namespace/project1/branch,namespace/project2</p>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'invalid-config',
    props: ['onInvalid'],
    data () {
      return {
        headerText: 'Invalid Configuration'
      }
    }
  }
</script>

// src/components/InvalidConfig/InvalidConfig.tsx
import styles from './InvalidConfig.module.css'

interface InvalidConfigProps {
  show: boolean
}

export function InvalidConfig({ show }: InvalidConfigProps) {
  if (!show) return null
  return (
    <div id="gcim-invalid-config" className={styles.container}>
      <div className={styles.header}>Invalid Configuration</div>
      <div className={styles.body}>
        <p>
          Make sure all configs are set. The following properties must be defined in the URL.
        </p>
        <p>
          Check{' '}
          <a
            href="https://github.com/emilianoeloi/gitlab-ci-dashboard/blob/master/README.md"
            target="_blank"
            rel="noreferrer"
          >
            README
          </a>{' '}
          for more configuration options.
        </p>
        <ul>
          <li>gitlab</li>
          <li>token</li>
          <li>projectsFile</li>
          <li>gitlabciProtocol (optional)</li>
          <li>hideSuccessCards (optional)</li>
          <li>hideVersion (optional)</li>
          <li>interval (optional)</li>
          <li>apiVersion (optional)</li>
        </ul>
        <p>
          <strong>projectsFile</strong> json pattern:
        </p>
        <pre className={styles.pre}>{`[
  {
    "description": "My project",
    "namespace": "group",
    "project": "my-project",
    "branch": "main"
  }
]`}</pre>
      </div>
      <div className={styles.example}>
        <p>
          Ex:{' '}
          <code>
            ?gitlab=gitlab.com&token=TOKEN&projectsFile=https://example.com/gitlab.json
          </code>
        </p>
      </div>
    </div>
  )
}
